In [2]:
import numpy as np

### Basic Concept
* Scalar is simply just a single number
* A Vector is an ordered array of numbers and can be in a row or a column
* A Matrix is an ordered 2D array of numbers and it has two indices (column and row)
* A Tenor is an array of numbers, arranged on a regular grid, with a variable number of axis. A Tensor has three or more indices

In [40]:
print "A scalar",np.random.randint(10)
print "A 3 element vector (1d)",np.random.random((3))
print "A matrix (2d)",np.random.random((2, 3))
print "A tensor (3d)",np.random.random((2, 3, 4))

A scalar 8
A 3 element vector (1d) [ 0.61504123  0.987176    0.58917967]
A matrix (2d) [[ 0.32916103  0.11796905  0.89125192]
 [ 0.82715935  0.74105354  0.17631332]]
A tensor (3d) [[[ 0.29390647  0.96088913  0.73391703  0.23745709]
  [ 0.42166192  0.17823166  0.30007681  0.33473825]
  [ 0.64236285  0.19337008  0.46741963  0.19627524]]

 [[ 0.89806775  0.9813773   0.01164324  0.2651135 ]
  [ 0.87998654  0.3732933   0.63914737  0.09273072]
  [ 0.27784164  0.78834407  0.47936228  0.35627476]]]


Generator a 3x2 matrics

In [5]:
a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

### Matrix-Scalar Operations
If you multiply, divide, subtract or add a scalar with a matrix, you just do this mathematical operation with every element of the matrix. 

In [8]:
a * 3

array([[ 0,  3],
       [ 6,  9],
       [12, 15]])

In [7]:
3 * a

array([[ 0,  3],
       [ 6,  9],
       [12, 15]])

### Matrix-Vector Multiplication
note the difference between * and dot

In [16]:
a * ([2,3])

array([[ 0,  3],
       [ 4,  9],
       [ 8, 15]])

In [42]:
a.dot([2,3])

array([ 3, 13, 23])

### Matrix-Matrix Addition and Subtraction

### Matrix-Matrix Multiplication

### Transpose
the mirror image of a matrix, along a 45 degree axis

In [19]:
a.T

array([[0, 2, 4],
       [1, 3, 5]])

### Identity Matrix
every Matrix that is multiplied by an Identity Matrix is equal to itself.

In [23]:
np.identity(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

### Inverse
A matrix that is multiplied by its inverse is equal to indentity. 

In [31]:
b = np.array([[3,4],[2,16]])
print b
inverse_b = np.linalg.inv(b)
print b
print b.dot(inverse_b)

[[ 3  4]
 [ 2 16]]
[[ 3  4]
 [ 2 16]]
[[ 1.  0.]
 [ 0.  1.]]


not all matrix has inverse, it has to be a square and not a Singular matrix

In [24]:
b = np.arange(9).reshape(3, 3)
print b
np.linalg.inv(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


LinAlgError: Singular matrix